# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8072866992085839a9891a8961528ae1f69e13da8002dca2bbbe5ae465b85c5af242b73f4cc031294f1e08aa1d3607c814de35105a1b29949b0b6b97a8f86e7

test:
  secret_key_base: 02c6d07cb9108eff591a260262073805d84084a822f5119647a2e6b66bbcdc530d775ad54bfae4e97da5dc8064ba7c5af70cefca1d4fb2480271b253ca328886

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
